### ISSUE TITLE
iOS: Message reply form textarea is wonky. Might benefit from hiding the preview?

### ISSUE THREAD

**Issue by mashcode** [BetaNYC/discourse#1]
Textarea field and keyboard cursor placement is flaky. Save and exit modal is broken. The behavior is most likely UI related. 

Screenshots upon request ;)

**Comment by noneck** [comment]
@mashcode please tell us the following:
- Device
- iOS version
- Browser

Also, can you add a screenshot? Thanks!

**Comment by mashcode** [comment]
Seems to be working much better now! My only suggestion would be the slow or smooth the transitions between states but this could be typical web display jerkiness.

**Comment by mashcode** [comment]
This is what it looks like. Looks good. Behaviors would be a separate issue

![image](https://cloud.githubusercontent.com/assets/91484/6201940/168ce1a4-b496-11e4-9227-ca59fe024449.jpg)
![image](https://cloud.githubusercontent.com/assets/91484/6201941/169a8002-b496-11e4-8b53-46af1904f71b.jpg)
